CREATE TABLE produtos (
  id BIGINT AUTO_INCREMENT NOT NULL,
   nome VARCHAR(150) NULL,
   descricao TEXT(1000) NOT NULL,
   preco DECIMAL NOT NULL,
   estoque INT NOT NULL,
   CONSTRAINT pk_produto PRIMARY KEY (id)
);